# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'barCodes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftHTTP', '~> 3.0.1'
  pod 'fluid-slider'
  pod 'TableViewReloadAnimation', '~> 0.0.5'
  pod 'M13Checkbox'
  # Pods for barCodes

end
